### ISSUE TITLE
unable to build models due to key error in M.dict

### ISSUE THREAD

**Issue by lessw2020** [Delay-Xili/F-Clip#3]
Hi - wanted to test out the models but in trying to run the demo, it's unable to build any of the models (HR, HG2) due to this key error:
![fclip_multihead_key_error](https://user-images.githubusercontent.com/46302957/115971044-1fab5200-a4fb-11eb-974d-b67a75bd21b7.JPG)

I'm working on debugging but if you have any insight, please let me know.
Thanks!

**Comment by lessw2020** [comment]
as best I can see so far, the config file base.yaml is not being included and thus there is no head or order in the config dict.
also, it seems the hr config file points to one on your server vs the install? 
~~~
def get_hr_config():
    cfg = Box()
    if M.width == 32:
        hr_yaml = "./config/w32_384x288_adam_lr1e-3.yaml"   #<--- I modified to point to existing file from earlier /home/dxl...
    # elif M.width == 48:
    #     hr_yaml = "/home/dxl/Code/faster-lcnn-master/config/w48_384x288_adam_lr1e-3.yaml"
    else:
        raise ValueError("no")
~~~

**Comment by lessw2020** [comment]
I was able to fix this issue by adding in a line to pull in the base yaml file:
![fclip_mode_arch_fix](https://user-images.githubusercontent.com/46302957/115971880-f2ad6e00-a4ff-11eb-9784-5e0d2582062e.JPG)

**Comment by lessw2020** [comment]
I then had to uncomment the C.io.model_initialize_file to get the checkpoint to load:
~~~
    def __init__(self, modeluse='HR', ckpt= './ckpt/HR/checkpoint.pth.tar'):
        from test import build_model, C, M

        if modeluse == 'HG1_D3':
            config_file = 'config/fclip_HG1_D3.yaml'
        elif modeluse == 'HG1':
            config_file = 'config/fclip_HG1.yaml'
        elif modeluse == 'HG2':
            config_file = 'config/fclip_HG2.yaml'
        elif modeluse == 'HG2_LB':
            config_file = 'config/fclip_HG2_LB.yaml'
        elif modeluse == 'HR':
            config_file = 'config/fclip_HR.yaml'
        else:
            raise ValueError("")

        #
        C.update(C.from_yaml(filename='config/base.yaml'))
        C.update(C.from_yaml(filename=config_file))
        #print(f"C = {C}")
        
        M.update(C.model)
        C.io.model_initialize_file = ckpt
~~~

**Comment by lessw2020** [comment]
With the above changes, the demo is now working!  Thanks for the nice work on developing this line detector!

**Comment by Delay-Xili** [comment]
Hi @lessw2020, sorry for the late reply, and thanks for your comments.
