### ISSUE TITLE
A little error of yaml path

### ISSUE THREAD

**Issue by Yifei6672** [Delay-Xili/F-Clip#4]
Firstly, thanks for the marvelous work and well written codes.

A little remind : when I was trying to run the code, I found that in the file **FClip/models/pose_hrnet.py**, at line 525, 
the path of yaml should be changed to my own path to run correctly.
![图像 1](https://user-images.githubusercontent.com/52418649/122638529-2505d100-d127-11eb-9928-346cca509e4b.png)

**Comment by Delay-Xili** [comment]
@Yifei6672 Thanks for the reminder, it fixed now.
