### ISSUE TITLE
The training parameters of using stacked hourglasses as backbone

### ISSUE THREAD

**Issue by Sun15194** [Delay-Xili/F-Clip#9]
Hello, thank you for your excellent code to help my research a lot.
I saw that 30 and 300 epochs were used respectively to train HG in the paper.
Could you tell me what the training parameters(lr, weight_decay, and Lr_decay_epoch) were set to at 30 epochs？

**Comment by Delay-Xili** [comment]
Just same as 300 epochs, the only difference is lr decay, my suggestion is decay the lr at 25-th, and 30-th epoch and train with 35 epochs.

**Comment by Sun15194** [comment]
Thank you very much for your timely reply. I have tried many experiments on 35 epochs. With the same parameters, a larger batch size will lead to an increase in sAP, which may indicate that the sAP of the network may increase with the increase of the number of epochs. I will try the experiment again on my machine.

**Comment by Sun15194** [comment]
In addition, if it is convenient, could you please tell me which epoch I can get the best training effect on when I use 300 epochs and corresponding parameters to train HourglassNet? This may help me debug the network better. Thank you very much.

**Comment by Delay-Xili** [comment]
The most peak value of sAP appears in the last 20 epochs of the total 300 epochs.
